/** Cat key → [nombre, precio, imagen relativa desde raíz del sitio] */
module.exports = {
  categories: [
    { key: 'abarrotes', name: 'Abarrotes', emoji: '🥫' },
    { key: 'bebidas', name: 'Bebidas', emoji: '🥤' },
    { key: 'lacteos', name: 'Lácteos', emoji: '🧀' },
    { key: 'carnes', name: 'Carnes', emoji: '🍗' },
    { key: 'viveres', name: 'Víveres', emoji: '🥔' },
    { key: 'verduras', name: 'Verduras', emoji: '🥬' },
    { key: 'limpieza', name: 'Higiene y Limpieza', emoji: '🧼' },
    { key: 'snacks', name: 'Snacks', emoji: '🍪' },
  ],
  products: [
    ['abarrotes', 'Aceite', 35, 'imagenes/aceite.PNG'],
    ['abarrotes', 'Arroz Pimco', 50, 'imagenes/arrozx2.PNG'],
    ['abarrotes', 'Avena Quaker', 40, 'imagenes/avena.PNG'],
    ['abarrotes', 'Maizena', 20, 'imagenes/harinademaiz.jpg'],
    ['abarrotes', 'Azúcar', 45, 'imagenes/azucar.PNG'],
    ['abarrotes', 'Pasta Espagueti', 60, 'imagenes/espaguetis.PNG'],
    ['abarrotes', 'Refisal', 120, 'imagenes/sal.PNG'],
    ['abarrotes', 'Huevos', 80, 'imagenes/huevos.jpeg'],
    ['abarrotes', 'Salsa de Tomate', 90, 'imagenes/salsatomate.jpg'],
    ['abarrotes', 'Mayonesa', 150, 'imagenes/mayonesa.PNG'],
    ['bebidas', 'Agua', 10, 'imagenes/agua.PNG'],
    ['bebidas', 'CocaCola', 35, 'imagenes/cocacola.jpg'],
    ['bebidas', 'KolaReal', 65, 'imagenes/kolareal.PNG'],
    ['bebidas', 'Jugos Frutop', 130, 'imagenes/frutopjugos.jpg'],
    ['bebidas', 'Jugos Petit', 750, 'imagenes/jugospetit.PNG'],
    ['bebidas', 'Jugo Rica', 420, 'imagenes/jugorica.jpg'],
    ['bebidas', 'Gatorade', 50, 'imagenes/gatorade.jpg'],
    ['bebidas', 'Jugos Santal', 110, 'imagenes/jugosantal.PNG'],
    ['bebidas', 'Sprite', 95, 'imagenes/sprite.PNG'],
    ['bebidas', 'Country Club', 280, 'imagenes/countryclub.PNG'],
    ['lacteos', 'Leche Listamil', 95, 'imagenes/lechelistamilk.jpg'],
    ['lacteos', 'Leche Evaporada', 250, 'imagenes/lecheevaporada.PNG'],
    ['lacteos', 'Leche Condensada', 130, 'imagenes/lechecondensada.PNG'],
    ['lacteos', 'Yogurt', 80, 'imagenes/yogurt.PNG'],
    ['lacteos', 'Mantequilla', 420, 'imagenes/mantequilla.jpg'],
    ['lacteos', 'Queso de Hoja', 190, 'imagenes/quesodehoja.jpg'],
    ['lacteos', 'Queso Rebanado', 160, 'imagenes/quesorebanado.jpg'],
    ['lacteos', 'Milkshake', 200, 'imagenes/milkshake.jpg'],
    ['lacteos', 'Cacao con Leche', 95, 'imagenes/cacaoleche.jpg'],
    ['lacteos', 'Queso Rallado', 180, 'imagenes/quesorallado.jpg'],
    ['carnes', 'Pollo', 250, 'imagenes/pollo.jpg'],
    ['carnes', 'Carne Salada', 380, 'imagenes/carnesalada.PNG'],
    ['carnes', 'Cerdo', 320, 'imagenes/cerdo.PNG'],
    ['carnes', 'Chuleta con hueso ahumada', 150, 'imagenes/chuletaconhuesoahumada.PNG'],
    ['carnes', 'Jamón', 280, 'imagenes/jamon.jpg'],
    ['carnes', 'Chuleta sin huesos', 200, 'imagenes/chuletasinhueso.PNG'],
    ['carnes', 'Costilla ahumada', 160, 'imagenes/costillaahumada.PNG'],
    ['carnes', 'Longaniza', 220, 'imagenes/longaniza.PNG'],
    ['carnes', 'Tocineta', 340, 'imagenes/tocineta.PNG'],
    ['carnes', 'Bacalao', 450, 'imagenes/bacalao.PNG'],
    ['viveres', 'Plátano Verde', 35, 'imagenes/platanosverdes.jpg'],
    ['viveres', 'Plátano Amarillo', 10, 'imagenes/platanosamarillo.jpg'],
    ['viveres', 'Yautía Coco', 20, 'imagenes/yautiacoco.PNG'],
    ['viveres', 'Papas', 75, 'imagenes/papas.jpeg'],
    ['viveres', 'Batata Criolla', 150, 'imagenes/batatacriolla.jpeg'],
    ['viveres', 'Yuca', 85, 'imagenes/yuca.PNG'],
    ['viveres', 'Guineos Verdes', 45, 'imagenes/guineoverde.PNG'],
    ['viveres', 'Ñame', 140, 'imagenes/ñame.PNG'],
    ['viveres', 'Auyama', 55, 'imagenes/auyama.jpeg'],
    ['viveres', 'Tayota', 70, 'imagenes/tayota.PNG'],
    ['verduras', 'Lechuga', 40, 'imagenes/lechuga.jpeg'],
    ['verduras', 'Tomate', 50, 'imagenes/tomates.jpeg'],
    ['verduras', 'Cebolla', 60, 'imagenes/cebolla.jpeg'],
    ['verduras', 'Zanahoria', 30, 'imagenes/zanahoria.jpeg'],
    ['verduras', 'Berenjena', 45, 'imagenes/berenjena.jpeg'],
    ['verduras', 'Ajo', 20, 'imagenes/ajo.jpeg'],
    ['verduras', 'Pimiento', 55, 'imagenes/pimiento.PNG'],
    ['verduras', 'Brócoli', 70, 'imagenes/brocoli.jpeg'],
    ['verduras', 'Pepino', 35, 'imagenes/pepinos.jpeg'],
    ['verduras', 'Aguacate', 40, 'imagenes/aguacate.jpeg'],
    ['limpieza', 'Jabón de Baño', 60, 'imagenes/jabondecuaba.PNG'],
    ['limpieza', 'Detergente Líquido', 180, 'imagenes/suavitel.PNG'],
    ['limpieza', 'Cloro', 90, 'imagenes/cloro.PNG'],
    ['limpieza', 'Suavizante', 120, 'imagenes/acebrillante.PNG'],
    ['limpieza', 'Mistolin', 130, 'imagenes/mistolin.PNG'],
    ['limpieza', 'Toallas Femeninas c/u', 40, 'imagenes/toallasfemeninas.PNG'],
    ['limpieza', 'Cepillo de Limpieza', 75, 'imagenes/papeldebaño.PNG'],
    ['limpieza', 'Cepillos Dental c/u', 110, 'imagenes/cepillos.jpg'],
    ['limpieza', 'Pasta Dental', 65, 'imagenes/pastadental.jpg'],
    ['limpieza', 'Acondicionador', 15, 'imagenes/shampoosedal.PNG'],
    ['snacks', 'Papas Lays', 35, 'imagenes/papaslays.PNG'],
    ['snacks', 'Galletas Oreo', 40, 'imagenes/oreo.PNG'],
    ['snacks', 'Chocolate Hersheys', 35, 'imagenes/hersheys.PNG'],
    ['snacks', 'Chicle Trident', 10, 'imagenes/trident.PNG'],
    ['snacks', 'Doritos', 70, 'imagenes/doritos.PNG'],
    ['snacks', 'Yummi Pops', 60, 'imagenes/yummipops.PNG'],
    ['snacks', 'Gomitas Trululu', 45, 'imagenes/trululus.PNG'],
    ['snacks', 'Cheetos', 55, 'imagenes/cheetos.PNG'],
    ['snacks', 'Chicles Clorets', 80, 'imagenes/clorets.jpeg'],
    ['snacks', 'Bolones c/u', 10, 'imagenes/bonbon.PNG'],
  ],
};
